name: pescador-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - pyzmq>=18.0
  - decorator>=4.0
  - msgpack-python>=1.0

  # optional, but required for testing
  - pytest
  - pytest-cov
  - pytest-timeout>=1.2
  - coverage
  - scipy
