name: pescador-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - joblib>=0.9
  - six>=1.8
  - pyzmq>=15.0
  - decorator>=4.0

  # optional, but required for testing
  - pytest<=4.0
  - pytest-cov
  - pytest-timeout>=1.2
  - coverage
